# Array Creation

In [2]:
import numpy as np
arr = np3.array([1,2,3,4,2])
print(arr)

[1 2 3 4 2]


In [3]:
tuples = (1,2,3,4,5,6,"h")
arr = np.array(tuples)
print(arr)

['1' '2' '3' '4' '5' '6' 'h']


In [4]:
zeros_array = np.zeros((4,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
ones_array = np.ones((5,10))
print(ones_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
print(ones_array +1)
print(ones_array -1)
print(ones_array *6)
print(ones_array //0)

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]]
[[inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]]


C:\Users\Ajay Patil\AppData\Local\Temp\ipykernel_23188\4230258447.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(ones_array //0)


In [6]:
empty_array = np.empty((4,2))

print(empty_array)


[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.75489891e-321]
 [1.78019082e-306 1.37959740e-306]]


In [7]:
arrange_array = np.arange(20)
print(arrange_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
arrange_array =arrange_array.reshape(5,4)
print(arrange_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [9]:
linspace_array = np.linspace(0,20,6)
print(linspace_array)

[ 0.  4.  8. 12. 16. 20.]


# Array Manipulation

In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print("------------------------------------")
reshaped_arr = arr.reshape((2,6))
print(reshaped_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
arr = reshaped_arr.transpose()
print(arr)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [12]:
first_array = np.arange(10)
second_array = np.arange(10,30, 2)
thid_array = np.array([[31,32,33,34,35,36,37,38,39,10]])
third_array = thid_array.flatten()

conacatinated_array = np.concatenate((first_array, second_array, third_array))
print(conacatinated_array)

[ 0  1  2  3  4  5  6  7  8  9 10 12 14 16 18 20 22 24 26 28 31 32 33 34
 35 36 37 38 39 10]


In [13]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
splitted_arr = np.split(arr,5)
print(splitted_arr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [14]:
flatten_array = np.array([[[1,2,3,45,6],[12,3,5,6,6],[11,36,69,85,46]]]).flatten()
print(flatten_array.ndim)
print(flatten_array)

1
[ 1  2  3 45  6 12  3  5  6  6 11 36 69 85 46]


In [15]:
arr = np.array([[[1],[2],[3]]])
print(arr.shape)
arr = np.squeeze(arr)
print(arr.shape)
print(arr)

(1, 3, 1)
(3,)
[1 2 3]


# Array Operation 

In [16]:
first_arr = np.array([1,2,3])
second_arr = np.array([4,5,6])
print(np.add(first_arr, second_arr))
print(np.subtract(first_arr, second_arr))
print(np.multiply(first_arr, second_arr))
print(np.divide(first_arr, second_arr))
print(np.power(first_arr, 2))
print(np.power(second_arr,2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[16 25 36]


In [17]:
print(np.dot(first_arr, second_arr))

32


In [18]:
m1 = np.array([[1,2],
               [3,4],
              [5,6]])
m2 = np.array([[5,6],
               [7,8]])
print(np.matmul(m1,m2))

[[19 22]
 [43 50]
 [67 78]]


In [19]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
dot_product_matrix = np.dot(A, B)
print("Dot product of matrices A and B:\n", dot_product_matrix)

Dot product of matrices A and B:
 [[19 22]
 [43 50]]


In [20]:
array = np.arange(10)
print(array)
print("mean", np.mean(array))
print("std", np.std(array))
print(f"sum {np.sum(array)}")
print(f"var : {np.var(array)}")

[0 1 2 3 4 5 6 7 8 9]
mean 4.5
std 2.8722813232690143
sum 45
var : 8.25


In [21]:
arr = np.arange(0,20,2)
print(arr)
print(f"max index: {np.argmax(arr)}")
print(f"min index : {np.argmin(arr)}")
print(f"Value at max index :{arr[np.argmax(arr)]}")
print(f"Value at min index : {arr[np.argmin(arr)]}")

[ 0  2  4  6  8 10 12 14 16 18]
max index: 9
min index : 0
Value at max index :18
Value at min index : 0


#  Linear Algebra

In [22]:
matrix = np.array([[1,2],
                  [3,4]])
print(np.linalg.inv(matrix))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
print(np.linalg.det(matrix))

-2.0000000000000004


In [24]:
matrix = np.array([[1,2],
                  [2,1]])
eigenValues, eigenVectors = np.linalg.eig(matrix)
print(eigenValues)
print(eigenVectors)

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [25]:
matrix = np.array([[1,2],
                  [3,4],
                  [5,6]])
U, S, VT = np.linalg.svd(matrix)
print("U", U)
print("S", S)
print("VT", VT)

U [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S [9.52551809 0.51430058]
VT [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Random Number generation

In [26]:
arr = np.random.rand(3,4)
print(arr)

[[0.02261403 0.53693922 0.99316839 0.180476  ]
 [0.38594221 0.49532494 0.09620376 0.37136483]
 [0.48637211 0.54068539 0.28631238 0.64909485]]


In [27]:
arr= np.random.randn(2,3)
print(arr)

[[-1.15058376 -1.46433633  1.66689547]
 [-0.80789108  2.06617625  0.14776562]]


In [28]:
print(np.random.randint(1,102, size = 10))

[68 58 32 38 68 67 83  3 21  3]


In [29]:
arr = np.arange(0,25)
print(arr)
print("------------------")
print(np.random.choice(arr,size=8))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
------------------
[ 7  5 21  5  9 11 24 21]


# Mathematical Functions:

In [30]:
print(np.sin(np.degrees(45)))
print(np.cos(45))
print(np.tan(45))

0.8060754911159176
0.5253219888177297
1.6197751905438615


In [31]:
arr = np.array([1,2,23,5])
print(np.exp(arr))
print(np.log(arr))
print(np.log10(arr))

[2.71828183e+00 7.38905610e+00 9.74480345e+09 1.48413159e+02]
[0.         0.69314718 3.13549422 1.60943791]
[0.         0.30103    1.36172784 0.69897   ]


In [32]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))


6
1
3.5
3.5


In [33]:
f = np.array([[2,3,2],
              [4,4,4]])
g = np.array([[1,2,30],
             [5,6,7],
             [7,8,9]])
print(np.matmul(f,g))

[[ 31  38  99]
 [ 52  64 184]]
